---
version: "3.8"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=Europe/Rome
      - USER=${TRANSMISSION_USER} #optional
      - PASS=${TRANSMISSION_PASSWORD} #optional
    volumes:
      - ${TRANSMISSION_CONFIG_PATH}:/config
      - ${TRANSMISSION_DOWNLOADS_PATH}:/downloads
      - ${TRANSMISSION_WATCH_PATH}:/watch
    ports:
      - ${TRANSMISSION_WEB_PORT}:9091
      - ${TRANSMISSION_TCP_PORT}:51413
      - ${TRANSMISSION_UDP_PORT}:51413/udp
    restart: unless-stopped
  
  pyload:
    image: lscr.io/linuxserver/pyload
    container_name: pyload
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=Europe/Rome
    volumes:
      - ${PYLOAD_CONFIG_PATH}:/config
      - ${PYLOAD_DOWNLOAD_PATH}:/downloads
    ports:
      - ${PYLOAD_WEB_PORT}:8000
      - ${PYLOAD_AUX_POR}:7227 #optional
    restart: unless-stopped