---
version: "3.8"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=${TRANSMISSION_USER} #optional
      - PASS=${TRANSMISSION_PASSWORD} #optional
      - WHITELIST=iplist #optional
      - HOST_WHITELIST=dnsnane list #optional
    volumes:
      - ${TRANSMISSION_CONFIG_PATH}:/config
      - ${TRANSMISSION_DOWNLOADS_PATH}:/downloads
      - ${TRANSMISSION_WATCH_PATH}:/watch
    ports:
      - ${TRANSMISSION_WEB_PORT}:9091
      - ${TRANSMISSION_TCP_PORT}:51413
      - ${TRANSMISSION_UDP_PORT}:51413/udp
    restart: unless-stopped